### PR TITLE
Offirmo/refactor build

### PR DESCRIPTION
**Pull request by Offirmo**
Not working :-/ Typescript UMD lacks the fallback to a global variable for whatever reason.

So using the typescript compiler was not such a good idea after all.

### CODE REVIEW

**Comment by Offirmo** [comment]
https://github.com/Microsoft/TypeScript/issues/8436

**Comment by Offirmo** [comment]
https://github.com/Microsoft/TypeScript/issues/8436

**Comment by lukechilds** [comment]
Hmmn, interesting.

I've got it working with rollup locally but using a module bundler just to convert module formats seems like a bit too much of a hack. Thanks for spending the time on this but I think I'm happy to leave it as is.

Developers who are comfortable installing modules of this size will almost definitely be using a modern module bundler that supports CommonJS modules :)

**Comment by Offirmo** [comment]
Actually I have an existing but complicated setting based on rollup working for a personal module. If I manage to clean it a bit, I'll share.

**Comment by lukechilds** [comment]
The setup isn't very complex with rollup, I just feel like using a module bundler when I don't have any modules to bundle and just using it for the module format output is kind of messy.

I've got a pretty simple config together, I'll push it up later today.

**Comment by lukechilds** [comment]
@Offirmo I think this is pretty clean: https://github.com/lukechilds/when-dom-ready/pull/10

Thoughts?

**Pull request closed without merging**
